apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      name: spring-app
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: tarundhiman/spring-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
          args:
            - "--spring.config.location=file:/config/application.properties"
      volumes:
        - name: config-volume
          configMap:
            name: spring-app-config
      restartPolicy: Always
      