apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tarun-spring-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'spring-app'
        metrics_path: /actuator/prometheus
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: spring-app
