apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - pods
      - endpoints
      - services
    verbs: ["get", "list", "watch"]
